name: Build and Release Executables

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile nc.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nc-${{ matrix.os }}
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - name: List downloaded files
      run: ls -lh

    - name: Upload Executables
      uses: softprops/action-gh-release@v2
      with:
        files: |
          nc.exe
          nc
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
