name: Build and Release Executables

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install PyArmor and PyInstaller
      run: pip install pyarmor pyinstaller

    - if: runner.os == 'Windows'
      name: Install UPX
      run: choco install upx

    - name: Obfuscate and build executable
      run: |
        # pyarmor gen --pack onefile --enable-jit --private --mix-str --assert-import --obf-code 2 nc.py
        pyarmor gen --pack onefile --enable-jit --private --assert-import nc.py
      shell: bash

    - name: Rename executable
      run: |
        if [[ ${{ runner.os }} == "Linux" ]]; then
          mv dist/nc dist/nc-linux
        elif [[ ${{ runner.os }} == "macOS" ]]; then
          mv dist/nc dist/nc-macos
        fi
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nc-${{ matrix.os }}
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all build artifacts
      uses: actions/download-artifact@v5
      with:
        merge-multiple: true

    - name: List downloaded files
      run: ls -lh

    - name: Upload executables
      uses: softprops/action-gh-release@v2
      with:
        files: |
          nc.exe
          nc-linux
          nc-macos
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
